/*
* generated by Xtext
*/
package com.lowcoupling.dono.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.lowcoupling.dono.services.DonoGrammarAccess;

public class DonoParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DonoGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.lowcoupling.dono.parser.antlr.internal.InternalDonoParser createParser(XtextTokenStream stream) {
		return new com.lowcoupling.dono.parser.antlr.internal.InternalDonoParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Doc";
	}
	
	public DonoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DonoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
