/*
 * generated by Xtext
 */
package com.lowcoupling.dono.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DonoUiModule extends com.lowcoupling.dono.ui.AbstractDonoUiModule {
	public DonoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
