/*
* generated by Xtext
*/
package com.lowcoupling.dono;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DonoStandaloneSetup extends DonoStandaloneSetupGenerated{

	public static void doSetup() {
		new DonoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

