/*
 * generated by Xtext
 */
package com.lowcoupling.dono;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DonoRuntimeModule extends com.lowcoupling.dono.AbstractDonoRuntimeModule {

}
