/*
 * generated by Xtext
 */
package com.lowcoupling.dono.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.lowcoupling.dono.ui.internal.DonoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DonoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DonoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DonoActivator.getInstance().getInjector(DonoActivator.COM_LOWCOUPLING_DONO_DONO);
	}
	
}
