/**
 * generated by Xtext
 */
package com.lowcoupling.dono.validation;

import com.lowcoupling.dono.validation.AbstractDonoValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DonoValidator extends AbstractDonoValidator {
}
